### PR TITLE
Swift 2.0

### PR DESCRIPTION
**Pull request by pietbrauer**
:fireworks: Opening again

### CODE REVIEW

**Comment by nscoding** [comment]
That's great @pietbrauer and updating scheme makes sense.

Can we squash the commits?

**Comment by nscoding** [comment]
hmm now that I look at it again we can't have Swift 1.2 with Xcode 7 right? (So I can't really upgrade master to Xcode 7 without updating the Swift code.

Am I correct about this?

**Comment by pietbrauer** [comment]
Yep, right. Thats why we have this `swift-2.0` branch right? Once Xcode 7 is the newest Xcode, I would merge this (so on the 16th). I will rebase the commits in a second.

**Comment by pietbrauer** [comment]
Squashed it

**Comment by nscoding** [comment]
Awesome, one question before I merge, why is the red image different?

**Comment by pietbrauer** [comment]
Thats a very good question. The test just failed on Xcode 7 it's not even a Swift test.

**Comment by nscoding** [comment]
I tried with 8.4 and the test is passing, so I assume UIBlurEffect changed slightly with iOS9. I will proceed and merge this one, thanks @pietbrauer

**Pull request merged**
