### PR TITLE
Use StaticString for assert-related methods.

### LINKED ISSUE #148: SwiftSupport L63
When building, I get: 'Cannot convert value of type 'String' to expected argument type 'StaticString''

I have installed FBSnapshotTestCase 2.0.7 via CocoaPods, and have also tried commit ee57dee37aa5be6ee6b307670a37f9bcce69e2e4. I build with Xcode 7.3-beta3.

In my CococaPods file I have the following defined:

```
use_frameworks!
platform :ios, '8.0'
```

If I remove that line I get three errors for the following lines in FBSnapshotTestController.m:
```
#import <FBSnapshotTestCase/UIImage+Compare.h>
#import <FBSnapshotTestCase/UIImage+Diff.h>
#import <FBSnapshotTestCase/UIImage+Snapshot.h>
```

The error I get is: "Use of private header from outside its module"

When I build with Xcode 7.2.1 I don't get the StringLiteral error, but I do get the three last errors.

### PR DESCRIPTION
**Pull request by puls**
This fixes #148, which seems to be a bit more pressing now that Xcode 7.3 is out.

### CODE REVIEW

**Comment by Pearapps** [comment]
Awesome

**Comment by nscoding** [comment]
Hey, thanks for fixing this, however there are still issues with the builds

**Comment by vandadnp** [comment]
+1 for fixing this. We cannot even build our test target due to this error.

**Comment by puls** [comment]
The latest commit fixes some configuration issues around the tests, but two of them are still failing on mismatched screenshots. I'm hoping @nscoding or one of the other locals can take a look and advise.

**Comment by nscoding** [comment]
@puls Can you re-record the images from the failing tests? (set `self.recordMode = YES;`) and run the tests for the two devices iPhone 5 and iPhone 6

**Comment by nscoding** [comment]
Thank you, I recreated it with #152 and fixed that last build issues.

**Comment by vandadnp** [comment]
Which POD version is this fix available in?

**Comment by nscoding** [comment]
In none yet, I will need to cut a new spec, I just want a double check that this PR fixes this issue.

**Comment by colinta** [comment]
@puls Doesn't seem to mind (since he closed this PR once the fix was implemented), but if I were him, I'd be disappointed that my commits were dropped in favor of *identical changes* from @nscoding.  It feels a little disingenuous to me.

**Comment by puls** [comment]
I didn't close the pull request—@nscoding did—but I think getting worked up about a trivial build fix is a bit unnecessary, especially when it needed more work to get merged in.

Hugs!

**Comment by colinta** [comment]
Ah, my mistake, bad scanning on my part.  But you still get full marks for being gracious!

**Pull request closed without merging**
