### PR TITLE
Remove custom module map for CP

### PR DESCRIPTION
**Pull request by neonichu**
Using `private header` in the module map while using non-quoted imports leads to "use of private header from outside its module" when building.

### CODE REVIEW

**Comment by nscoding** [comment]
Hey thanks for the PR,

I introduced this with #127 #129 as a workaround because the project wouldn't build but not sure what's 
the right way. So we just remove the map and everything will work?

**Comment by neonichu** [comment]
Interesting, we actually removed the `private header` declarations from the module map CocoaPods itself generates to work around behavioural changes in Xcode 7.1

**Comment by nscoding** [comment]
Any update on this one?

**Comment by neonichu** [comment]
Not really. I'm currently using this branch for a Swift project as I'm otherwise getting the "use of private header from outside its module" error mentioned above with both Xcode 7.1 and 7.2

**Comment by steam** [comment]
I'm seeing the same issue when using `Nimble-Snapshots` and CocoaPoads 1.0.0.beta.3. Is the plan to merge this PR in a new version of `FBSnapshotTestCase`?

**Comment by steam** [comment]
I should note that `Nimble-Snapshots` 3.0.0 uses `FBSnapshotTestCase` 2.0.7.

**Comment by nscoding** [comment]
I cloned this PR and then I get a bunch of errors when trying to build the demo app, these are the same errors I tried to resolve with the custom map

**Comment by neonichu** [comment]
@nscoding I'll have a look at the demo app issues.

**Comment by neonichu** [comment]
@nscoding I see the issue, it is related to https://github.com/CocoaPods/CocoaPods/issues/4420 which is only resolved in CocoaPods 1.0 (which I was actually using in my earlier tests already). So this PR should not be merged until the CP 1.0 final release.

**Comment by steam** [comment]
Good call @neonichu. As a work around I was able to add `  pod 'FBSnapshotTestCase', git: 'https://github.com/neonichu/ios-snapshot-test-case.git', commit: '9e88da88a7a3df2f80838449a5f1e71830179218'` to my Podfile above `Nimble-Snapshot` and the  dependencies resolve and errors go away. Temporary, but nice that it will work until the CP 1.0 final release.

**Comment by nscoding** [comment]
Thanks for looking at this, I will keep this open and wait for 1.0.

**Comment by bgerstle** [comment]
I've also been able to work around this error by adding the following to our Podfile:

``` ruby
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['WARNING_CFLAGS'] = '$(inherited) -Wno-error=private-header' if target.name == 'FBSnapshotTestCase'
        end
    end
end
```

Using CocoaPods 1.0.0-beta6, Xcode 7.3.

**Comment by itsthejb** [comment]
@bgerstle thanks for the workaround! This was really holding us back from 7.3

**Comment by Krizai** [comment]
1.0 is released. Can you please incorporate this change ?

**Comment by neonichu** [comment]
Updated the PR so that CI now also works again.

**Comment by nscoding** [comment]
Great! Looks great I am going to merge and cut a spec.

**Comment by nscoding** [comment]
@neonichu I still get a bunch of errors on the FBSnapshotTestCaseDemo, even though I generated the workspace with cocoapods 1.0.0, any ideas?

**Comment by neonichu** [comment]
hm, not sure, how can I reproduce them? I thought it was being build as part of CI?

**Comment by nscoding** [comment]
I thought that as well, yes you open FBSnapshotTestCase.xcworkspace in FBSnapshotTestCaseDemo and build the app with Xcode 7.3.1

**Comment by orta** [comment]
That works for me, just done it from a fresh clone of master, `pod install`'d with the mac app at 1.0.0

screen shot 2016-05-11 at 3 42 23 pm

**Comment by nscoding** [comment]
@orta I can try on another machine, until then can you try to bump FBSnapshotTestCase.podspec to 2.1.1 and 'pod install' ?

**Comment by nscoding** [comment]
It works on another machine, unclear, I'll investigate a bit more

**Pull request merged**
